"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { verifyLoginMfa } from "../../lib/auth";
import { setLibraryToken, setUserData } from "../../lib/cookies";

export default function MfaPage() {
  const router = useRouter();

  const [code, setCode] = useState("");
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError("");

    if (code.length !== 6) {
      setError("Enter a 6-digit verification code");
      return;
    }

    try {
      setLoading(true);

      const email = localStorage.getItem("mfaEmail");

      if (!email) {
        throw new Error("MFA session expired. Please log in again.");
      }

      const response = await verifyLoginMfa(email, code);
      const token = response.data.token;
      const user = response.data.user;

      await setLibraryToken(token);
      await setUserData(user);

      localStorage.removeItem("mfaEmail");

      if (user.role === "Admin") {
        router.push("/admin/dashboard");
      } else {
        router.push("/dashboard");
      }
    } catch (err: any) {
      setError(err.message || "Invalid MFA code. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="min-h-screen bg-gradient-to-br from-[#f4f7f5] via-[#edf3f0] to-[#e6ede9] flex items-center justify-center p-4 sm:p-6 md:p-10 font-sans">
      <div className="w-full max-w-md bg-white rounded-[32px] shadow-[0_20px_50px_rgba(15,23,42,0.06)] overflow-hidden border border-slate-100/80 backdrop-blur-sm p-8 sm:p-10 flex flex-col justify-center">
        
        {/* Header App Icon & Context */}
        <div className="flex flex-col items-center mb-8">
          <div className="w-12 h-12 rounded-2xl bg-gradient-to-tr from-blue-600 to-indigo-600 flex items-center justify-center font-black tracking-tighter text-xl text-white shadow-md shadow-blue-500/20 mb-4">
            L
          </div>
          <h1 className="text-2xl font-extrabold text-slate-900 tracking-tight sm:text-3xl text-center">
            Two-Step Verification
          </h1>
          <p className="text-sm text-slate-400 mt-2 font-medium text-center max-w-[280px]">
            Enter the 6-digit protection code generated by your Authenticator app
          </p>
        </div>

        {/* Dynamic Contextual Error Feedback Panel */}
        {error && (
          <div className="mb-6 p-4 bg-rose-50/60 backdrop-blur-sm border border-rose-100 text-rose-900 rounded-2xl text-sm font-medium flex items-center gap-3 shadow-sm animate-in fade-in slide-in-from-top-2 duration-200">
            <span className="flex h-7 w-7 items-center justify-center rounded-full bg-rose-500 text-white font-bold text-xs shrink-0 select-none">!</span>
            <span className="text-rose-800 font-semibold">{error}</span>
          </div>
        )}

        {/* Input Interface Area */}
        <form onSubmit={handleSubmit} className="space-y-6">
          <div className="flex flex-col gap-2">
            <label className="text-xs font-bold text-slate-500 tracking-wider uppercase pl-1 text-center select-none">
              Verification Security Code
            </label>
            <div className="relative">
              <input
                type="text"
                maxLength={6}
                value={code}
                onChange={(e) => setCode(e.target.value.replace(/\D/g, ""))}
                placeholder="000000"
                className="w-full bg-slate-50/60 border border-slate-200 rounded-2xl p-4 text-center tracking-[0.4em] font-black text-2xl text-slate-800 placeholder-slate-300 outline-none transition-all duration-200 focus:border-blue-600 focus:bg-white focus:ring-4 focus:ring-blue-500/10"
                required
                disabled={loading}
                autoFocus
              />
            </div>
          </div>

          <div className="pt-2">
            <button
              type="submit"
              disabled={loading}
              className="w-full bg-gradient-to-r from-blue-600 to-indigo-600 hover:from-blue-700 hover:to-indigo-700 text-white py-3.5 rounded-2xl text-sm font-bold tracking-wide shadow-[0_4px_14px_rgba(37,99,235,0.25)] hover:shadow-[0_6px_20px_rgba(37,99,235,0.35)] transition-all duration-200 active:scale-[0.99] disabled:from-slate-200 disabled:to-slate-200 disabled:text-slate-400 disabled:shadow-none disabled:cursor-not-allowed"
            >
              {loading ? "Confirming Security Code..." : "Verify & Sign In"}
            </button>
          </div>
        </form>

        {/* Navigation Return Hook */}
        <div className="text-center mt-8">
          <button 
            type="button" 
            onClick={() => {
              localStorage.removeItem("mfaEmail");
              router.push("/login");
            }}
            className="text-sm text-blue-600 font-extrabold hover:text-blue-700 hover:underline transition"
          >
            Back to login option screen
          </button>
        </div>

      </div>
    </div>
  );
}